- name: Turbo Build APK (The Ultimate Force Fix)
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          cd ./pwa-apk
          # 1. Pehle project update karo taaki checksum error na aaye
          yes | bubblewrap update --yes
          # 2. Phir build karo, saare prompts ko 'yes' bolte hue
          bubblewrap build --yes --accept_tos
